# -*- coding: utf-8 -*-
"""Assignment7ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RhUqunxjAeGCO3r8dJhICHp-UfkeZLO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

df = pd.read_csv("score.csv")
print(df.head())

df.info()

X = df[['Hours']]
y = df['Scores']

plt.scatter(df['Hours'], df['Scores'])
plt.title('Hours vs Scores')
plt.xlabel('Hours')
plt.ylabel('Scores')
plt.show()

model = LinearRegression()
model.fit(X, y)

from sklearn.model_selection import train_test_split
X_test, X_train, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

X = model.predict(X_test)

y = model.predict(X_test)

print(X_test)